# name: CI

# on:
#   push:
#     branches:
#       - main
#   pull_request:

# permissions:
#   actions: read
#   contents: read

# jobs:
#   main:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           filter: tree:0
#           fetch-depth: 0

#       # This enables task distribution via Nx Cloud
#       # Run this command as early as possible, before dependencies are installed
#       # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
#       # Uncomment this line to enable task distribution
#       # - run: npx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

#       # Cache node_modules
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           cache: 'npm'

#       - run: npm ci --legacy-peer-deps

#       # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
#       # - run: npx nx-cloud record -- echo Hello World
#       - run: npx nx run-many -t lint test build
#       # Nx Cloud recommends fixes for failures to help you get CI green faster. Learn more: https://nx.dev/ci/features/self-healing-ci
#       - run: npx nx fix-ci
#         if: always()
name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - run: npx nx run-many -t lint test build

      - name: Build Docker images
        run: |
          docker build -t taskmanager-fe:latest .
          docker build -f Dockerfile.api -t taskmanager-be:latest .

      - name: Verify Docker images
        run: |
          docker images | grep taskmanager
          docker run --rm taskmanager-fe:latest ls -la dist/apps/dashboard/browser/
          docker run --rm taskmanager-be:latest ls -la dist/

      - run: npx nx fix-ci
        if: always()
